
-- ============================================================
-- ÉNUMÉRATIONS simulées via des tables de référence
-- ============================================================

IF OBJECT_ID('dbo.REF_TYPE_PLAN', 'U') IS NULL
CREATE TABLE REF_TYPE_PLAN (
    CODE        NVARCHAR(20) PRIMARY KEY,
    LIBELLE     NVARCHAR(100) NOT NULL
);
INSERT INTO REF_TYPE_PLAN VALUES
    ('STARTER',    'Starter — jusqu''à 5 utilisateurs'),
    ('PRO',        'Pro — jusqu''à 20 utilisateurs'),
    ('ENTERPRISE', 'Enterprise — illimité');
GO

IF OBJECT_ID('dbo.REF_ROLE', 'U') IS NULL
CREATE TABLE REF_ROLE (
    CODE        NVARCHAR(20) PRIMARY KEY,
    LIBELLE     NVARCHAR(100) NOT NULL
);
INSERT INTO REF_ROLE VALUES
    ('ADMIN',       'Administrateur — accès total'),
    ('SUPERVISEUR', 'Superviseur — gestion terrain'),
    ('TECHNICIEN',  'Technicien — missions uniquement');
GO

IF OBJECT_ID('dbo.REF_STATUT_INTERVENTION', 'U') IS NULL
CREATE TABLE REF_STATUT_INTERVENTION (
    CODE        NVARCHAR(20) PRIMARY KEY,
    LIBELLE     NVARCHAR(100) NOT NULL,
    ORDRE       TINYINT NOT NULL
);
INSERT INTO REF_STATUT_INTERVENTION VALUES
    ('CREEE',      'Créée',       1),
    ('EN_ATTENTE', 'En attente',  2),
    ('EN_COURS',   'En cours',    3),
    ('TERMINEE',   'Terminée',    4),
    ('VALIDEE',    'Validée',     5),
    ('FACTUREE',   'Facturée',    6);
GO

IF OBJECT_ID('dbo.REF_TYPE_INTERVENTION', 'U') IS NULL
CREATE TABLE REF_TYPE_INTERVENTION (
    CODE        NVARCHAR(20) PRIMARY KEY,
    LIBELLE     NVARCHAR(100) NOT NULL
);
INSERT INTO REF_TYPE_INTERVENTION VALUES
    ('CURATIF',    'Intervention curative'),
    ('PREVENTIF',  'Intervention préventive'),
    ('URGENCE',    'Intervention urgente');
GO

IF OBJECT_ID('dbo.REF_TYPE_PHOTO', 'U') IS NULL
CREATE TABLE REF_TYPE_PHOTO (
    CODE        NVARCHAR(20) PRIMARY KEY,
    LIBELLE     NVARCHAR(100) NOT NULL
);
INSERT INTO REF_TYPE_PHOTO VALUES
    ('AVANT', 'Photo avant intervention'),
    ('APRES', 'Photo après intervention'),
    ('AUTRE', 'Autre photo');
GO

IF OBJECT_ID('dbo.REF_STATUT_FACTURE', 'U') IS NULL
CREATE TABLE REF_STATUT_FACTURE (
    CODE        NVARCHAR(30) PRIMARY KEY,
    LIBELLE     NVARCHAR(100) NOT NULL
);
INSERT INTO REF_STATUT_FACTURE VALUES
    ('BROUILLON',         'Brouillon'),
    ('ENVOYEE',           'Envoyée au client'),
    ('PAYEE_PARTIELLEMENT','Paiement partiel reçu'),
    ('PAYEE',             'Payée intégralement'),
    ('EN_RETARD',         'En retard de paiement');
GO

IF OBJECT_ID('dbo.REF_TYPE_CONTRAT', 'U') IS NULL
CREATE TABLE REF_TYPE_CONTRAT (
    CODE        NVARCHAR(20) PRIMARY KEY,
    LIBELLE     NVARCHAR(100) NOT NULL
);
INSERT INTO REF_TYPE_CONTRAT VALUES
    ('CDI',        'Contrat à durée indéterminée'),
    ('CDD',        'Contrat à durée déterminée'),
    ('JOURNALIER', 'Travailleur journalier');
GO

IF OBJECT_ID('dbo.REF_TYPE_MOUVEMENT', 'U') IS NULL
CREATE TABLE REF_TYPE_MOUVEMENT (
    CODE        NVARCHAR(10) PRIMARY KEY,
    LIBELLE     NVARCHAR(100) NOT NULL
);
INSERT INTO REF_TYPE_MOUVEMENT VALUES
    ('ENTREE', 'Entrée en stock'),
    ('SORTIE', 'Sortie de stock');
GO

-- ============================================================
-- ÉTAPE 1 — TABLE LOCATAIRE (aucune dépendance)
-- ============================================================

IF OBJECT_ID('dbo.LOCATAIRE', 'U') IS NULL
CREATE TABLE LOCATAIRE (
    ID_LOCATAIRE        UNIQUEIDENTIFIER    NOT NULL DEFAULT NEWSEQUENTIALID(),
    NOM                 NVARCHAR(200)       NOT NULL,
    SLUG                NVARCHAR(100)       NOT NULL,   -- ex: eneo-nord-pme
    TYPE_PLAN           NVARCHAR(20)        NOT NULL DEFAULT 'STARTER',
    MODULES_ACTIFS      NVARCHAR(500)       NOT NULL DEFAULT 'CORE', -- CSV: CORE,FACTURATION,STOCK
    CODE_PAYS           CHAR(2)             NOT NULL DEFAULT 'CM',
    PREFIXE_TELEPHONE   NVARCHAR(5)         NOT NULL DEFAULT '+237',
    EST_ACTIF           BIT                 NOT NULL DEFAULT 1,
    DATE_CREATION       DATETIME2           NOT NULL DEFAULT SYSDATETIME(),
    DATE_MODIFICATION   DATETIME2           NULL,

    CONSTRAINT PK_LOCATAIRE         PRIMARY KEY (ID_LOCATAIRE),
    CONSTRAINT UQ_LOCATAIRE_SLUG    UNIQUE (SLUG),
    CONSTRAINT FK_LOCATAIRE_PLAN    FOREIGN KEY (TYPE_PLAN)
        REFERENCES REF_TYPE_PLAN(CODE)
);
GO

-- ============================================================
-- ÉTAPE 2 — TABLE UTILISATEUR (dépend de LOCATAIRE)
-- ============================================================

IF OBJECT_ID('dbo.UTILISATEUR', 'U') IS NULL
CREATE TABLE UTILISATEUR (
    ID_UTILISATEUR      UNIQUEIDENTIFIER    NOT NULL DEFAULT NEWSEQUENTIALID(),
    ID_LOCATAIRE        UNIQUEIDENTIFIER    NOT NULL,
    NOM_COMPLET         NVARCHAR(200)       NOT NULL,
    TELEPHONE           NVARCHAR(20)        NOT NULL,  -- identifiant principal
    EMAIL               NVARCHAR(200)       NULL,
    MOT_DE_PASSE_HASH   NVARCHAR(500)       NOT NULL,
    ROLE                NVARCHAR(20)        NOT NULL DEFAULT 'TECHNICIEN',
    TOKEN_FCM           NVARCHAR(500)       NULL,      -- Firebase Cloud Messaging
    EST_ACTIF           BIT                 NOT NULL DEFAULT 1,
    DERNIERE_CONNEXION  DATETIME2           NULL,
    DATE_CREATION       DATETIME2           NOT NULL DEFAULT SYSDATETIME(),
    DATE_MODIFICATION   DATETIME2           NULL,
    EST_SUPPRIME        BIT                 NOT NULL DEFAULT 0,

    CONSTRAINT PK_UTILISATEUR                   PRIMARY KEY (ID_UTILISATEUR),
    CONSTRAINT UQ_UTILISATEUR_TEL_LOCATAIRE     UNIQUE (ID_LOCATAIRE, TELEPHONE),
    CONSTRAINT FK_UTILISATEUR_LOCATAIRE         FOREIGN KEY (ID_LOCATAIRE)
        REFERENCES LOCATAIRE(ID_LOCATAIRE),
    CONSTRAINT FK_UTILISATEUR_ROLE              FOREIGN KEY (ROLE)
        REFERENCES REF_ROLE(CODE)
);
GO

-- ============================================================
-- ÉTAPE 3 — TABLE INTERVENTION (dépend de LOCATAIRE, UTILISATEUR)
-- ============================================================

IF OBJECT_ID('dbo.INTERVENTION', 'U') IS NULL
CREATE TABLE INTERVENTION (
    ID_INTERVENTION     UNIQUEIDENTIFIER    NOT NULL DEFAULT NEWSEQUENTIALID(),
    ID_LOCAL            NVARCHAR(50)        NULL,      -- GUID offline généré côté mobile
    ID_LOCATAIRE        UNIQUEIDENTIFIER    NOT NULL,
    REFERENCE           NVARCHAR(30)        NOT NULL,  -- ex: INT-2025-00142
    TITRE               NVARCHAR(300)       NOT NULL,
    DESCRIPTION         NVARCHAR(MAX)       NULL,
    TYPE                NVARCHAR(20)        NOT NULL,
    PRIORITE            TINYINT             NOT NULL DEFAULT 2, -- 1=Urgent 2=Normal 3=Faible
    STATUT              NVARCHAR(20)        NOT NULL DEFAULT 'CREEE',
    NOM_CLIENT          NVARCHAR(200)       NULL,
    ADRESSE             NVARCHAR(500)       NULL,
    LATITUDE            DECIMAL(10,7)       NULL,
    LONGITUDE           DECIMAL(10,7)       NULL,
    DATE_PLANIFIEE      DATETIME2           NULL,
    DATE_DEBUT          DATETIME2           NULL,
    DATE_FIN            DATETIME2           NULL,
    DATE_VALIDATION     DATETIME2           NULL,
    ID_VALIDATEUR       UNIQUEIDENTIFIER    NULL,
    URL_SIGNATURE       NVARCHAR(500)       NULL,      -- URL blob signature client
    NOTES               NVARCHAR(MAX)       NULL,
    ID_CREATEUR         UNIQUEIDENTIFIER    NOT NULL,
    DATE_CREATION       DATETIME2           NOT NULL DEFAULT SYSDATETIME(),
    DATE_MODIFICATION   DATETIME2           NULL,
    EST_SUPPRIME        BIT                 NOT NULL DEFAULT 0,

    CONSTRAINT PK_INTERVENTION              PRIMARY KEY (ID_INTERVENTION),
    CONSTRAINT UQ_INTERVENTION_REF_TENANT   UNIQUE (ID_LOCATAIRE, REFERENCE),
    CONSTRAINT FK_INTERVENTION_LOCATAIRE    FOREIGN KEY (ID_LOCATAIRE)
        REFERENCES LOCATAIRE(ID_LOCATAIRE),
    CONSTRAINT FK_INTERVENTION_CREATEUR     FOREIGN KEY (ID_CREATEUR)
        REFERENCES UTILISATEUR(ID_UTILISATEUR),
    CONSTRAINT FK_INTERVENTION_VALIDATEUR   FOREIGN KEY (ID_VALIDATEUR)
        REFERENCES UTILISATEUR(ID_UTILISATEUR),
    CONSTRAINT FK_INTERVENTION_TYPE         FOREIGN KEY (TYPE)
        REFERENCES REF_TYPE_INTERVENTION(CODE),
    CONSTRAINT FK_INTERVENTION_STATUT       FOREIGN KEY (STATUT)
        REFERENCES REF_STATUT_INTERVENTION(CODE),
    CONSTRAINT CK_INTERVENTION_PRIORITE    CHECK (PRIORITE IN (1, 2, 3)),
    CONSTRAINT CK_INTERVENTION_COORDS      CHECK (
        (LATITUDE IS NULL AND LONGITUDE IS NULL)
        OR (LATITUDE BETWEEN -90 AND 90 AND LONGITUDE BETWEEN -180 AND 180)
    )
);
GO

-- ============================================================
-- ÉTAPE 4 — TABLE AFFECTATION_INTERVENTION
--           (dépend de INTERVENTION, UTILISATEUR)
-- ============================================================

IF OBJECT_ID('dbo.AFFECTATION_INTERVENTION', 'U') IS NULL
CREATE TABLE AFFECTATION_INTERVENTION (
    ID_AFFECTATION      UNIQUEIDENTIFIER    NOT NULL DEFAULT NEWSEQUENTIALID(),
    ID_INTERVENTION     UNIQUEIDENTIFIER    NOT NULL,
    ID_TECHNICIEN       UNIQUEIDENTIFIER    NOT NULL,
    DATE_AFFECTATION    DATETIME2           NOT NULL DEFAULT SYSDATETIME(),
    EST_PRINCIPAL       BIT                 NOT NULL DEFAULT 0,

    CONSTRAINT PK_AFFECTATION_INTERVENTION      PRIMARY KEY (ID_AFFECTATION),
    CONSTRAINT UQ_AFFECTATION_INTERV_TECH       UNIQUE (ID_INTERVENTION, ID_TECHNICIEN),
    CONSTRAINT FK_AFFECTATION_INTERVENTION      FOREIGN KEY (ID_INTERVENTION)
        REFERENCES INTERVENTION(ID_INTERVENTION),
    CONSTRAINT FK_AFFECTATION_TECHNICIEN        FOREIGN KEY (ID_TECHNICIEN)
        REFERENCES UTILISATEUR(ID_UTILISATEUR)
);
GO

-- ============================================================
-- ÉTAPE 5 — TABLE PHOTO_INTERVENTION
--           (dépend de INTERVENTION, UTILISATEUR)
-- ============================================================

IF OBJECT_ID('dbo.PHOTO_INTERVENTION', 'U') IS NULL
CREATE TABLE PHOTO_INTERVENTION (
    ID_PHOTO            UNIQUEIDENTIFIER    NOT NULL DEFAULT NEWSEQUENTIALID(),
    ID_INTERVENTION     UNIQUEIDENTIFIER    NOT NULL,
    URL_BLOB            NVARCHAR(1000)      NOT NULL,
    TYPE_PHOTO          NVARCHAR(20)        NOT NULL DEFAULT 'AUTRE',
    DATE_PRISE          DATETIME2           NOT NULL,
    ID_UPLOADEUR        UNIQUEIDENTIFIER    NOT NULL,
    LATITUDE            DECIMAL(10,7)       NULL,
    LONGITUDE           DECIMAL(10,7)       NULL,

    CONSTRAINT PK_PHOTO_INTERVENTION        PRIMARY KEY (ID_PHOTO),
    CONSTRAINT FK_PHOTO_INTERVENTION        FOREIGN KEY (ID_INTERVENTION)
        REFERENCES INTERVENTION(ID_INTERVENTION),
    CONSTRAINT FK_PHOTO_UPLOADEUR           FOREIGN KEY (ID_UPLOADEUR)
        REFERENCES UTILISATEUR(ID_UTILISATEUR),
    CONSTRAINT FK_PHOTO_TYPE                FOREIGN KEY (TYPE_PHOTO)
        REFERENCES REF_TYPE_PHOTO(CODE)
);
GO

-- ============================================================
-- ÉTAPE 6 — TABLE FACTURE  [MODULE FACTURATION]
--           (dépend de LOCATAIRE, INTERVENTION)
-- ============================================================

IF OBJECT_ID('dbo.FACTURE', 'U') IS NULL
CREATE TABLE FACTURE (
    ID_FACTURE          UNIQUEIDENTIFIER    NOT NULL DEFAULT NEWSEQUENTIALID(),
    ID_LOCATAIRE        UNIQUEIDENTIFIER    NOT NULL,
    ID_INTERVENTION     UNIQUEIDENTIFIER    NULL,       -- peut être créée sans intervention
    REFERENCE           NVARCHAR(30)        NOT NULL,   -- ex: FAC-2025-00042
    STATUT              NVARCHAR(30)        NOT NULL DEFAULT 'BROUILLON',
    NOM_CLIENT          NVARCHAR(200)       NOT NULL,
    SOUS_TOTAL_XAF      DECIMAL(15,2)       NOT NULL DEFAULT 0,
    TAUX_TVA            DECIMAL(5,2)        NOT NULL DEFAULT 19.25, -- TVA Cameroun
    TOTAL_XAF           DECIMAL(15,2)       NOT NULL DEFAULT 0,
    DATE_ECHEANCE       DATE                NULL,
    DATE_PAIEMENT       DATETIME2           NULL,
    URL_PDF             NVARCHAR(500)       NULL,
    DATE_CREATION       DATETIME2           NOT NULL DEFAULT SYSDATETIME(),
    DATE_MODIFICATION   DATETIME2           NULL,

    CONSTRAINT PK_FACTURE                   PRIMARY KEY (ID_FACTURE),
    CONSTRAINT UQ_FACTURE_REF_TENANT        UNIQUE (ID_LOCATAIRE, REFERENCE),
    CONSTRAINT FK_FACTURE_LOCATAIRE         FOREIGN KEY (ID_LOCATAIRE)
        REFERENCES LOCATAIRE(ID_LOCATAIRE),
    CONSTRAINT FK_FACTURE_INTERVENTION      FOREIGN KEY (ID_INTERVENTION)
        REFERENCES INTERVENTION(ID_INTERVENTION),
    CONSTRAINT FK_FACTURE_STATUT            FOREIGN KEY (STATUT)
        REFERENCES REF_STATUT_FACTURE(CODE),
    CONSTRAINT CK_FACTURE_TAUX_TVA         CHECK (TAUX_TVA >= 0 AND TAUX_TVA <= 100),
    CONSTRAINT CK_FACTURE_MONTANTS         CHECK (SOUS_TOTAL_XAF >= 0 AND TOTAL_XAF >= 0)
);
GO

-- ============================================================
-- ÉTAPE 7 — TABLE LIGNE_FACTURE (dépend de FACTURE)
-- ============================================================

IF OBJECT_ID('dbo.LIGNE_FACTURE', 'U') IS NULL
CREATE TABLE LIGNE_FACTURE (
    ID_LIGNE            UNIQUEIDENTIFIER    NOT NULL DEFAULT NEWSEQUENTIALID(),
    ID_FACTURE          UNIQUEIDENTIFIER    NOT NULL,
    DESCRIPTION         NVARCHAR(500)       NOT NULL,
    QUANTITE            DECIMAL(10,2)       NOT NULL,
    PRIX_UNITAIRE       DECIMAL(15,2)       NOT NULL,
    TOTAL_XAF           DECIMAL(15,2)       NOT NULL,

    CONSTRAINT PK_LIGNE_FACTURE             PRIMARY KEY (ID_LIGNE),
    CONSTRAINT FK_LIGNE_FACTURE             FOREIGN KEY (ID_FACTURE)
        REFERENCES FACTURE(ID_FACTURE) ON DELETE CASCADE,
    CONSTRAINT CK_LIGNE_QUANTITE           CHECK (QUANTITE > 0),
    CONSTRAINT CK_LIGNE_PRIX               CHECK (PRIX_UNITAIRE >= 0)
);
GO

-- ============================================================
-- ÉTAPE 8 — TABLE EMPLOYE  [MODULE RH]
--           (dépend de LOCATAIRE, UTILISATEUR)
-- ============================================================

IF OBJECT_ID('dbo.EMPLOYE', 'U') IS NULL
CREATE TABLE EMPLOYE (
    ID_EMPLOYE          UNIQUEIDENTIFIER    NOT NULL DEFAULT NEWSEQUENTIALID(),
    ID_LOCATAIRE        UNIQUEIDENTIFIER    NOT NULL,
    ID_UTILISATEUR      UNIQUEIDENTIFIER    NULL,       -- optionnel: l'employé peut ne pas avoir de compte
    NUMERO_EMPLOYE      NVARCHAR(30)        NOT NULL,
    SALAIRE_BASE_XAF    DECIMAL(15,2)       NOT NULL,
    TYPE_CONTRAT        NVARCHAR(20)        NOT NULL,
    DATE_EMBAUCHE       DATE                NOT NULL,
    NUMERO_CNPS         NVARCHAR(50)        NULL,
    EST_ACTIF           BIT                 NOT NULL DEFAULT 1,
    DATE_CREATION       DATETIME2           NOT NULL DEFAULT SYSDATETIME(),
    DATE_MODIFICATION   DATETIME2           NULL,

    CONSTRAINT PK_EMPLOYE                   PRIMARY KEY (ID_EMPLOYE),
    CONSTRAINT UQ_EMPLOYE_NUM_TENANT        UNIQUE (ID_LOCATAIRE, NUMERO_EMPLOYE),
    CONSTRAINT FK_EMPLOYE_LOCATAIRE         FOREIGN KEY (ID_LOCATAIRE)
        REFERENCES LOCATAIRE(ID_LOCATAIRE),
    CONSTRAINT FK_EMPLOYE_UTILISATEUR       FOREIGN KEY (ID_UTILISATEUR)
        REFERENCES UTILISATEUR(ID_UTILISATEUR),
    CONSTRAINT FK_EMPLOYE_CONTRAT           FOREIGN KEY (TYPE_CONTRAT)
        REFERENCES REF_TYPE_CONTRAT(CODE),
    CONSTRAINT CK_EMPLOYE_SALAIRE          CHECK (SALAIRE_BASE_XAF >= 0)
);
GO

-- ============================================================
-- ÉTAPE 9 — TABLE ARTICLE_STOCK  [MODULE STOCK]
--           (dépend de LOCATAIRE)
-- ============================================================

IF OBJECT_ID('dbo.ARTICLE_STOCK', 'U') IS NULL
CREATE TABLE ARTICLE_STOCK (
    ID_ARTICLE          UNIQUEIDENTIFIER    NOT NULL DEFAULT NEWSEQUENTIALID(),
    ID_LOCATAIRE        UNIQUEIDENTIFIER    NOT NULL,
    NOM                 NVARCHAR(200)       NOT NULL,
    REFERENCE           NVARCHAR(100)       NULL,
    UNITE               NVARCHAR(30)        NOT NULL,   -- pièce, kg, m, litre…
    STOCK_ACTUEL        DECIMAL(15,2)       NOT NULL DEFAULT 0,
    STOCK_MINIMUM       DECIMAL(15,2)       NOT NULL DEFAULT 0,  -- seuil d'alerte
    PRIX_UNITAIRE_XAF   DECIMAL(15,2)       NULL,
    DATE_CREATION       DATETIME2           NOT NULL DEFAULT SYSDATETIME(),
    DATE_MODIFICATION   DATETIME2           NULL,

    CONSTRAINT PK_ARTICLE_STOCK             PRIMARY KEY (ID_ARTICLE),
    CONSTRAINT FK_ARTICLE_LOCATAIRE         FOREIGN KEY (ID_LOCATAIRE)
        REFERENCES LOCATAIRE(ID_LOCATAIRE),
    CONSTRAINT CK_ARTICLE_STOCK_ACTUEL     CHECK (STOCK_ACTUEL >= 0),
    CONSTRAINT CK_ARTICLE_STOCK_MIN        CHECK (STOCK_MINIMUM >= 0)
);
GO

-- ============================================================
-- ÉTAPE 10 — TABLE MOUVEMENT_STOCK
--            (dépend de ARTICLE_STOCK, INTERVENTION, UTILISATEUR)
-- ============================================================

IF OBJECT_ID('dbo.MOUVEMENT_STOCK', 'U') IS NULL
CREATE TABLE MOUVEMENT_STOCK (
    ID_MOUVEMENT        UNIQUEIDENTIFIER    NOT NULL DEFAULT NEWSEQUENTIALID(),
    ID_ARTICLE          UNIQUEIDENTIFIER    NOT NULL,
    ID_INTERVENTION     UNIQUEIDENTIFIER    NULL,       -- NULL = mouvement manuel
    TYPE_MOUVEMENT      NVARCHAR(10)        NOT NULL,
    QUANTITE            DECIMAL(15,2)       NOT NULL,
    ID_OPERATEUR        UNIQUEIDENTIFIER    NOT NULL,
    DATE_MOUVEMENT      DATETIME2           NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT PK_MOUVEMENT_STOCK           PRIMARY KEY (ID_MOUVEMENT),
    CONSTRAINT FK_MOUVEMENT_ARTICLE         FOREIGN KEY (ID_ARTICLE)
        REFERENCES ARTICLE_STOCK(ID_ARTICLE),
    CONSTRAINT FK_MOUVEMENT_INTERVENTION    FOREIGN KEY (ID_INTERVENTION)
        REFERENCES INTERVENTION(ID_INTERVENTION),
    CONSTRAINT FK_MOUVEMENT_OPERATEUR       FOREIGN KEY (ID_OPERATEUR)
        REFERENCES UTILISATEUR(ID_UTILISATEUR),
    CONSTRAINT FK_MOUVEMENT_TYPE            FOREIGN KEY (TYPE_MOUVEMENT)
        REFERENCES REF_TYPE_MOUVEMENT(CODE),
    CONSTRAINT CK_MOUVEMENT_QUANTITE       CHECK (QUANTITE > 0)
);
GO

-- ============================================================
-- ÉTAPE 11 — TABLE POSITION_GPS  [MODULE GPS]
--            (dépend de UTILISATEUR)
-- ============================================================

IF OBJECT_ID('dbo.POSITION_GPS', 'U') IS NULL
CREATE TABLE POSITION_GPS (
    ID_POSITION         UNIQUEIDENTIFIER    NOT NULL DEFAULT NEWSEQUENTIALID(),
    ID_UTILISATEUR      UNIQUEIDENTIFIER    NOT NULL,
    LATITUDE            DECIMAL(10,7)       NOT NULL,
    LONGITUDE           DECIMAL(10,7)       NOT NULL,
    PRECISION_METRES    DECIMAL(8,2)        NULL,
    HORODATAGE          DATETIME2           NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT PK_POSITION_GPS              PRIMARY KEY (ID_POSITION),
    CONSTRAINT FK_POSITION_UTILISATEUR      FOREIGN KEY (ID_UTILISATEUR)
        REFERENCES UTILISATEUR(ID_UTILISATEUR),
    CONSTRAINT CK_POSITION_LATITUDE        CHECK (LATITUDE BETWEEN -90 AND 90),
    CONSTRAINT CK_POSITION_LONGITUDE       CHECK (LONGITUDE BETWEEN -180 AND 180)
);
GO

-- ============================================================
-- INDEX DE PERFORMANCE
-- ============================================================

-- INTERVENTION : filtre principal par tenant + statut
CREATE INDEX IX_INTERVENTION_TENANT_STATUT
    ON INTERVENTION(ID_LOCATAIRE, STATUT)
    INCLUDE (TITRE, DATE_PLANIFIEE, PRIORITE);

-- INTERVENTION : déduplication offline
CREATE INDEX IX_INTERVENTION_ID_LOCAL
    ON INTERVENTION(ID_LOCAL)
    WHERE ID_LOCAL IS NOT NULL;

-- AFFECTATION : requêtes planning technicien
CREATE INDEX IX_AFFECTATION_TECHNICIEN_DATE
    ON AFFECTATION_INTERVENTION(ID_TECHNICIEN, DATE_AFFECTATION);

-- UTILISATEUR : filtrage par rôle dans un tenant
CREATE INDEX IX_UTILISATEUR_TENANT_ROLE
    ON UTILISATEUR(ID_LOCATAIRE, ROLE)
    WHERE EST_SUPPRIME = 0;

-- FACTURE : suivi paiements et alertes retard
CREATE INDEX IX_FACTURE_TENANT_STATUT
    ON FACTURE(ID_LOCATAIRE, STATUT, DATE_ECHEANCE);


-- MOUVEMENT_STOCK : historique par article
CREATE INDEX IX_MOUVEMENT_ARTICLE_DATE
    ON MOUVEMENT_STOCK(ID_ARTICLE, DATE_MOUVEMENT DESC);

-- POSITION_GPS : dernier point par technicien (tracking temps réel)
CREATE INDEX IX_POSITION_UTILISATEUR_HORODATAGE
    ON POSITION_GPS(ID_UTILISATEUR, HORODATAGE DESC);

GO

-- ============================================================
-- TRIGGERS : mise à jour automatique de DATE_MODIFICATION
-- ============================================================

CREATE OR ALTER TRIGGER TRG_LOCATAIRE_UPDATE
ON LOCATAIRE AFTER UPDATE AS
    UPDATE LOCATAIRE SET DATE_MODIFICATION = SYSDATETIME()
    WHERE ID_LOCATAIRE IN (SELECT ID_LOCATAIRE FROM inserted);
GO

CREATE OR ALTER TRIGGER TRG_UTILISATEUR_UPDATE
ON UTILISATEUR AFTER UPDATE AS
    UPDATE UTILISATEUR SET DATE_MODIFICATION = SYSDATETIME()
    WHERE ID_UTILISATEUR IN (SELECT ID_UTILISATEUR FROM inserted);
GO

CREATE OR ALTER TRIGGER TRG_INTERVENTION_UPDATE
ON INTERVENTION AFTER UPDATE AS
    UPDATE INTERVENTION SET DATE_MODIFICATION = SYSDATETIME()
    WHERE ID_INTERVENTION IN (SELECT ID_INTERVENTION FROM inserted);
GO

CREATE OR ALTER TRIGGER TRG_FACTURE_UPDATE
ON FACTURE AFTER UPDATE AS
    UPDATE FACTURE SET DATE_MODIFICATION = SYSDATETIME()
    WHERE ID_FACTURE IN (SELECT ID_FACTURE FROM inserted);
GO

CREATE OR ALTER TRIGGER TRG_EMPLOYE_UPDATE
ON EMPLOYE AFTER UPDATE AS
    UPDATE EMPLOYE SET DATE_MODIFICATION = SYSDATETIME()
    WHERE ID_EMPLOYE IN (SELECT ID_EMPLOYE FROM inserted);
GO

CREATE OR ALTER TRIGGER TRG_ARTICLE_STOCK_UPDATE
ON ARTICLE_STOCK AFTER UPDATE AS
    UPDATE ARTICLE_STOCK SET DATE_MODIFICATION = SYSDATETIME()
    WHERE ID_ARTICLE IN (SELECT ID_ARTICLE FROM inserted);
GO

-- ============================================================
-- TRIGGER : mise à jour automatique de STOCK_ACTUEL
-- après chaque mouvement (entrée/sortie)
-- ============================================================

CREATE OR ALTER TRIGGER TRG_MOUVEMENT_STOCK_UPDATE_STOCK
ON MOUVEMENT_STOCK AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;

    -- Entrées : on additionne
    UPDATE ARTICLE_STOCK
    SET STOCK_ACTUEL = STOCK_ACTUEL + i.QUANTITE,
        DATE_MODIFICATION = SYSDATETIME()
    FROM ARTICLE_STOCK a
    INNER JOIN inserted i ON a.ID_ARTICLE = i.ID_ARTICLE
    WHERE i.TYPE_MOUVEMENT = 'ENTREE';

    -- Sorties : on soustrait (avec vérification anti-négatif)
    UPDATE ARTICLE_STOCK
    SET STOCK_ACTUEL = STOCK_ACTUEL - i.QUANTITE,
        DATE_MODIFICATION = SYSDATETIME()
    FROM ARTICLE_STOCK a
    INNER JOIN inserted i ON a.ID_ARTICLE = i.ID_ARTICLE
    WHERE i.TYPE_MOUVEMENT = 'SORTIE'
      AND a.STOCK_ACTUEL >= i.QUANTITE;

    -- Erreur si stock insuffisant pour une sortie
    IF EXISTS (
        SELECT 1
        FROM ARTICLE_STOCK a
        INNER JOIN inserted i ON a.ID_ARTICLE = i.ID_ARTICLE
        WHERE i.TYPE_MOUVEMENT = 'SORTIE'
          AND a.STOCK_ACTUEL < i.QUANTITE
    )
    BEGIN
        RAISERROR('Stock insuffisant pour effectuer cette sortie.', 16, 1);
        ROLLBACK TRANSACTION;
    END
END;
GO

-- ============================================================
-- VUES UTILES
-- ============================================================

-- Vue : interventions avec nom du technicien principal
CREATE OR ALTER VIEW VUE_INTERVENTION_TECHNICIEN AS
    SELECT
        i.ID_INTERVENTION,
        i.ID_LOCATAIRE,
        i.REFERENCE,
        i.TITRE,
        i.TYPE,
        i.PRIORITE,
        i.STATUT,
        i.NOM_CLIENT,
        i.DATE_PLANIFIEE,
        i.DATE_DEBUT,
        i.DATE_FIN,
        i.DATE_VALIDATION,
        u.NOM_COMPLET   AS NOM_TECHNICIEN_PRINCIPAL,
        u.TELEPHONE     AS TEL_TECHNICIEN_PRINCIPAL,
        c.NOM_COMPLET   AS NOM_CREATEUR
    FROM INTERVENTION i
    LEFT JOIN AFFECTATION_INTERVENTION a
        ON a.ID_INTERVENTION = i.ID_INTERVENTION AND a.EST_PRINCIPAL = 1
    LEFT JOIN UTILISATEUR u ON u.ID_UTILISATEUR = a.ID_TECHNICIEN
    LEFT JOIN UTILISATEUR c ON c.ID_UTILISATEUR = i.ID_CREATEUR
    WHERE i.EST_SUPPRIME = 0;
GO

-- Vue : articles en rupture imminente (stock <= seuil minimum)
CREATE OR ALTER VIEW VUE_ARTICLES_ALERTE_STOCK AS
    SELECT
        a.ID_ARTICLE,
        a.ID_LOCATAIRE,
        l.NOM           AS NOM_LOCATAIRE,
        a.NOM           AS NOM_ARTICLE,
        a.REFERENCE,
        a.UNITE,
        a.STOCK_ACTUEL,
        a.STOCK_MINIMUM,
        a.PRIX_UNITAIRE_XAF
    FROM ARTICLE_STOCK a
    INNER JOIN LOCATAIRE l ON l.ID_LOCATAIRE = a.ID_LOCATAIRE
    WHERE a.STOCK_ACTUEL <= a.STOCK_MINIMUM;
GO

-- Vue : factures en retard
CREATE OR ALTER VIEW VUE_FACTURES_EN_RETARD AS
    SELECT
        f.ID_FACTURE,
        f.ID_LOCATAIRE,
        l.NOM           AS NOM_LOCATAIRE,
        f.REFERENCE,
        f.NOM_CLIENT,
        f.TOTAL_XAF,
        f.DATE_ECHEANCE,
        DATEDIFF(DAY, f.DATE_ECHEANCE, CAST(SYSDATETIME() AS DATE)) AS JOURS_RETARD
    FROM FACTURE f
    INNER JOIN LOCATAIRE l ON l.ID_LOCATAIRE = f.ID_LOCATAIRE
    WHERE f.STATUT NOT IN ('PAYEE', 'BROUILLON')
      AND f.DATE_ECHEANCE < CAST(SYSDATETIME() AS DATE);
GO


ALTER TABLE PHOTO_INTERVENTION
ADD COMMENTAIRE VARCHAR(2000)

CREATE TABLE REF_TYPE_DEPENSE_INTERVENTION
(
    CODE        NVARCHAR(20) PRIMARY KEY,
    LIBELLE     NVARCHAR(100) NOT NULL
)

CREATE TABLE REF_CATEGORIE_DEPENSE
(
    CODE        NVARCHAR(20) PRIMARY KEY,
    LIBELLE     NVARCHAR(100) NOT NULL,
	ACTIF bit not null default 1
)

CREATE TABLE DEPENSE_INTERVENTION
(
	ID_DEPENSE UNIQUEIDENTIFIER    NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	ID_INTERVENTION UNIQUEIDENTIFIER NOT NULL,
	ID_EMPLOYE UNIQUEIDENTIFIER,
	ID_SAISIE_PAR UNIQUEIDENTIFIER,
	REFERENCE VARCHAR(20) NOT NULL,
	TYPE_DEPENSE NVARCHAR(20) NOT NULL,
	MONTANT_XAF   DECIMAL(15,2)       NOT NULL DEFAULT 0,
	NOTE	VARCHAR(2000),
	DATE_DEPENSE DATETIME,
	DATE_CREATION DATETIME NOT NULL,
	CONSTRAINT FK_DEPENSE_INTERVENTION FOREIGN KEy(ID_INTERVENTION) REFERENCES INTERVENTION(ID_INTERVENTION),
	CONSTRAINT FK_DEPENSE_INTERVENTION_EMPLOYE FOREIGN KEy(ID_EMPLOYE) REFERENCES EMPLOYE(ID_EMPLOYE),
	CONSTRAINT FK_DEPENSE_INTERVENTION_UTILISATEUR FOREIGN KEy(ID_SAISIE_PAR) REFERENCES UTILISATEUR(ID_UTILISATEUR),
	CONSTRAINT FK_DEPENSE_TYPE_DEPENSE FOREIGN KEy(TYPE_DEPENSE) REFERENCES REF_TYPE_DEPENSE_INTERVENTION(CODE)
)


CREATE TABLE DEPENSE
(
	ID_DEPENSE UNIQUEIDENTIFIER    NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	ID_SAISIE_PAR UNIQUEIDENTIFIER,
	REFERENCE VARCHAR(20) NOT NULL,
	TYPE_DEPENSE NVARCHAR(20) NOT NULL,
	MONTANT_XAF   DECIMAL(15,2)       NOT NULL DEFAULT 0,
	NOTE	VARCHAR(2000),
	DATE_DEPENSE DATETIME,
	DATE_CREATION DATETIME NOT NULL,
	CONSTRAINT FK_DEPENSE_UTILISATEUR FOREIGN KEy(ID_SAISIE_PAR) REFERENCES UTILISATEUR(ID_UTILISATEUR),
	CONSTRAINT FK_DEPENSE_TYPE_DEPENSE FOREIGN KEy(TYPE_DEPENSE) REFERENCES REF_TYPE_DEPENSE_INTERVENTION(CODE)
)



INSERT INTO REF_TYPE_DEPENSE_INTERVENTION
(
CODE,
LIBELLE
)
SELECT tmp.CODE, tmp.LIBELLE
FROM	(
	SELECT 'RATION' CODE, 'Raion' LIBELLE
	UNION ALL
	SELECT 'TRANSPORT' CODE, 'Transport' LIBELLE
) tmp
LEFT JOIN	REF_TYPE_DEPENSE_INTERVENTION r
	ON r.CODE = tmp.CODE
WHERE r.CODE IS NULL

GO

-- pour la table categorie depense, il faut peut-être prevoir un flag pour distinguer les dépenses lié à une intervention.